pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.mozilla.org/maven2/' }
    }
}

rootProject.name = "VHB_QMS_Android_Display_2.2.0_GeckoView"
include ':app'
